package com.bankservices.constants;

public enum WallexUrlContant {

	// key
	WALLEX_X_API_KEY("WALLEX_X_API_KEY"),
	WALLEX_ACCESS_KEY_ID("WALLEX_ACCESS_KEY_ID"),
	WALLEX_SECRET_ACCESS_KEY("WALLEX_SECRET_ACCESS_KEY"),
	
	// URL
	WALLEX_BASE_URL("WALLEX_BASE_URL"), 
	WALLEX_SIMPLE_PAYMENT_QUOTE_URL("WALLEX_SIMPLE_PAYMENT_QUOTE"),
	WALLEX_SIMPLE_PAYMENT_URL("WALLEX_SIMPLE_PAYMENT"), 
	WALLEX_SIGNUP_URL("WALLEX_SIGNUP"),
	WALLEX_BENEFICIARIES_CREATE_URL("WALLEX_BENEFICIARIES_CREATE"),
	WALLEX_BENEFICIARIES_REQUIREMENTS_URL("WALLEX_BENEFICIARIES_REQUIREMENTS"),
	WALLEX_ACCOUNT_BALANCE_URL("WALLEX_ACCOUNT_BALANCE_URL"),
	WALLEX_GET_TRANSFER_LIST_URL("WALLEX_GET_TRANSFER_LIST_URL"),
	WALLEX_TOKEN_URL("WALLEX_TOKEN"),
	
	// WEB HOOKS
	WALLEX_GET_USER_URL("WALLEX_GET_USER_URL"),
	WALLEX_GET_COLLECTION_URL("WALLEX_GET_COLLECTION_URL"), 
	WALLEX_GET_COLLECTION_ACCOUNT_URL("WALLEX_GET_COLLECTION_ACCOUNT_URL"),
	WALLEX_GET_TRANSFER_URL("WALLEX_GET_TRANSFER_URL"),
	
	;

	private final String value;

	private WallexUrlContant(String value) {
		this.value = value;
	}

	public String getValue() {
		return value;
	}
}
